import { Component, inject, signal } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { DecimalPipe, PercentPipe, JsonPipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Api, Models } from '../core/api';
import { deliveryLabel, patternLabel, sideLabel, zoneLabel } from '../core/football-labels';
@Component({standalone:true,imports:[RouterLink,DecimalPipe,PercentPipe,JsonPipe,FormsModule],templateUrl:'./analysis.html'})
export class Analysis {
 api=inject(Api);route=inject(ActivatedRoute);id='';view=signal('summary');run=signal<Models['Run']|null>(null);summary=signal<Models['Summary']|null>(null);corners=signal<Models['Corner'][]>([]);patterns=signal<Models['Pattern'][]>([]);quality=signal<Models['Quality']|null>(null);model=signal<Models['ModelResult']|null>(null);report=signal<Models['Report']|null>(null);agentResult=signal<Models['AgentResponse']|null>(null);plan=signal<string[]>([]);busy=signal(true);reportBusy=signal(false);agentBusy=signal(false);error=signal('');reportError=signal('');agentError=signal('');player='';side='';delivery='';cluster='';question='';askedQuestion=signal('');
 tabs=[['summary','Resumen'],['map','Mapa de córners'],['patterns','Patrones'],['report','Reporte táctico'],['quality','Calidad'],['agent','Asistente de evidencia']];
 readonly objectiveOrder=['scr15','short_direct','delivery_zone','corner_count'];
 readonly sideLabel=sideLabel;readonly zoneLabel=zoneLabel;readonly deliveryLabel=deliveryLabel;readonly patternLabel=patternLabel;
 private loadRequest=0;
 constructor(){this.route.paramMap.subscribe(params=>{this.view.set(params.get('view')??'summary');const id=params.get('id')??'';if(id!==this.id){this.id=id;void this.load();}});}
 async load(){const request=++this.loadRequest;const id=this.id;this.busy.set(true);this.error.set('');this.report.set(null);this.agentResult.set(null);this.run.set(null);this.summary.set(null);this.quality.set(null);try{const [run,s,c,p,q,m,plan]=await Promise.all([this.api.run(id),this.api.summary(id),this.api.corners(id),this.api.patterns(id),this.api.quality(id),this.api.model(id),this.api.plan(id)]);if(request!==this.loadRequest)return;this.run.set(run);this.summary.set(s);this.corners.set(c);this.patterns.set(p);this.quality.set(q);this.model.set(m);this.plan.set(plan);}catch(e){if(request===this.loadRequest)this.error.set(String(e));}finally{if(request===this.loadRequest)this.busy.set(false);}}
 filtered(){return this.corners().filter(c=>c.spatial_valid&&(!this.player||c.player===this.player)&&(!this.side||c.side===this.side)&&(!this.delivery||c.delivery===this.delivery)&&(!this.cluster||String(c.cluster)===this.cluster));}
 destinationGroups(summary:Models['Summary']){return summary.zones.filter(group=>group.label!=='no_disponible');}
 zonedCorners(summary:Models['Summary']){return this.destinationGroups(summary).reduce((total,group)=>total+group.count,0);}
 objectiveWinners(){return [...(this.model()?.evaluations.objective_winners??[])].sort((a,b)=>this.objectiveOrder.indexOf(a.objective)-this.objectiveOrder.indexOf(b.objective));}
 scr15UsesLeagueReference(){return this.objectiveWinners().some(result=>result.objective==='scr15'&&result.winner==='league_reference');}
 objectiveLabel(objective:string){return ({scr15:'SCR-15',short_direct:'Córner corto/directo',delivery_zone:'Zona de envío',corner_count:'Cantidad de córners'} as Record<string,string>)[objective]??objective;}
 winnerLabel(winner:string){return ({candidate:'Modelo candidato seleccionado',league_reference:'Referencia liguera',historical_baseline:'Histórico del equipo',not_modeled:'No modelado',not_modelled:'No modelado',logistic_regression:'Regresión logística',poisson_regression:'Regresión de Poisson'} as Record<string,string>)[winner]??winner.replaceAll('_',' ');}
 justificationLabel(justification:string){return justification.replace('candidate passed','El candidato superó').replace('development windows','ventanas de desarrollo').replace('persistence rho','persistencia rho').replace('support min','soporte mínimo').replace('teams min','equipos mínimos').replace('persistence','persistencia').replace('variance/mean','varianza/media').replace('conditional dispersion','dispersión condicional').replace('family','familia');}
 // Translate only known data labels in provider text; never change evidence IDs or downloaded JSON.
 footballText(text:string){return text.replace(/Patron \d+, zona (franja_cercana|franja_central|franja_lejana|fuera_area)/g,(_,zone:string)=>`Envíos hacia ${zoneLabel(zone).toLowerCase()}`).replace(/zona (franja_cercana|franja_central|franja_lejana|fuera_area)/g,(_,zone:string)=>zoneLabel(zone).toLowerCase()).replace(/\b(franja_cercana|franja_central|franja_lejana|fuera_area|y_bajo|y_alto)\b/g,value=>value.startsWith('y_')?sideLabel(value).toLowerCase():zoneLabel(value).toLowerCase());}
 async generate(){const id=this.id;this.reportBusy.set(true);this.reportError.set('');try{const report=await this.api.report(id);if(id===this.id)this.report.set(report);}catch(e){if(id===this.id)this.reportError.set(String(e));}finally{this.reportBusy.set(false);}}
 async askAgent(){const question=this.question.trim();if(!question)return;const id=this.id;this.agentBusy.set(true);this.agentError.set('');this.agentResult.set(null);try{const result=await this.api.agent(id,question);if(id===this.id){this.agentResult.set(result);this.askedQuestion.set(question);}}catch(e){if(id===this.id)this.agentError.set(String(e));}finally{this.agentBusy.set(false);}}
 download(){const report=this.report();if(!report)return;const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='cornerscout-reporte.json';link.click();URL.revokeObjectURL(url);}
}
