/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Teams */
        get: operations["getTeams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Matches */
        get: operations["getMatches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scouting-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Run */
        post: operations["createRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scouting-runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scouting-runs/{run_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["getSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scouting-runs/{run_id}/corners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Corners */
        get: operations["getCorners"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scouting-runs/{run_id}/patterns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Patterns */
        get: operations["getPatterns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scouting-runs/{run_id}/quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quality */
        get: operations["getQuality"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scouting-runs/{run_id}/model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model */
        get: operations["getModel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scouting-runs/{run_id}/report-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report Plan */
        get: operations["getReportPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scouting-runs/{run_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report */
        post: operations["createReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scouting-runs/{run_id}/agent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask Agent */
        post: operations["askAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentRequest */
        AgentRequest: {
            /** Question */
            question: string;
        };
        /** AgentResponse */
        AgentResponse: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "deterministic" | "openai";
            /** Fallback Reason */
            fallback_reason?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "answered" | "out_of_scope" | "error";
            /** Answer */
            answer: string;
            /** Evidence Ids */
            evidence_ids: string[];
            /** Tool Calls */
            tool_calls: number;
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /**
             * Total Tokens
             * @default 0
             */
            total_tokens: number;
            /** Traces */
            traces?: components["schemas"]["AgentTrace"][];
        };
        /** AgentTrace */
        AgentTrace: {
            /**
             * Kind
             * @default tool
             * @constant
             */
            kind: "tool";
            /** Tool */
            tool: string;
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /** Arguments Validated */
            arguments_validated: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "error";
            /** Result Summary */
            result_summary?: {
                [key: string]: unknown;
            } | null;
            /** Error Type */
            error_type?: string | null;
            /** Error Code */
            error_code?: string | null;
            /** Latency Ms */
            latency_ms: number;
        };
        /** Claim */
        Claim: {
            /** Text */
            text: string;
            /** Evidence Ids */
            evidence_ids: string[];
        };
        /** Corner */
        Corner: {
            /** Match Id */
            match_id: number;
            /** Event Id */
            event_id: string;
            /** Player */
            player: string;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** End X */
            end_x: number;
            /** End Y */
            end_y: number;
            /** Side */
            side: string;
            /** Delivery */
            delivery: string;
            /** Zone */
            zone: string;
            /** Height */
            height: string;
            /** Shot Within 15S */
            shot_within_15s: boolean | null;
            /** Xg */
            xg: number | null;
            /** Valid Sequence */
            valid_sequence: boolean;
            /** Spatial Valid */
            spatial_valid: boolean;
            /** End Reason */
            end_reason: string;
            /** Shot Ids */
            shot_ids: string[];
            /** Restart Ids */
            restart_ids: string[];
            /** Possession Change Ids */
            possession_change_ids: string[];
            /** Cluster */
            cluster?: number | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Detail */
            detail: string | {
                [key: string]: unknown;
            }[];
        };
        /** Evidence */
        Evidence: {
            /** Id */
            id: string;
            /** Description */
            description: string;
            /** Value */
            value: string;
            /** Event Ids */
            event_ids?: string[];
        };
        /** Group */
        Group: {
            /** Label */
            label: string;
            /** Count */
            count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Match */
        Match: {
            /** Match Id */
            match_id: number;
            /** Match Date */
            match_date: string;
            /** Kick Off */
            kick_off: string;
            /** Home Team */
            home_team: string;
            /** Away Team */
            away_team: string;
        };
        /** ModelEvaluation */
        ModelEvaluation: {
            /** Objective Winners */
            objective_winners: components["schemas"]["ObjectiveWinner"][];
            /** Temporal Metrics */
            temporal_metrics: components["schemas"]["TemporalMetric"][];
        };
        /** ModelResult */
        ModelResult: {
            /** Served */
            served: string;
            /** Probability */
            probability: number | null;
            /** Evaluation Scope */
            evaluation_scope: string;
            evaluations: components["schemas"]["ModelEvaluation"];
        };
        /** Narrative */
        Narrative: {
            /** Observations */
            observations: components["schemas"]["Claim"][];
            /** Recommendations */
            recommendations: components["schemas"]["Claim"][];
        };
        /** ObjectiveWinner */
        ObjectiveWinner: {
            /** Objective */
            objective: string;
            /** Winner */
            winner: string;
            /** Modeled */
            modeled: boolean;
            /** Justification */
            justification: string;
        };
        /** Pattern */
        Pattern: {
            /** Cluster */
            cluster: number;
            /** Count */
            count: number;
            /** Evaluable */
            evaluable: number;
            /** Scr15 */
            scr15: number | null;
            /** Xg Per Corner */
            xg_per_corner: number | null;
            /** Dominant Zone */
            dominant_zone: string;
            /** Main Taker */
            main_taker: string;
            /** Example Event Ids */
            example_event_ids: string[];
            /** Snapshot */
            snapshot: string;
        };
        /** Quality */
        Quality: {
            /**
             * Provider
             * @default StatsBomb Open Data
             */
            provider: string;
            /**
             * Season
             * @default LaLiga 2015/16
             */
            season: string;
            /**
             * Competition Id
             * @default 11
             */
            competition_id: number;
            /**
             * Season Id
             * @default 27
             */
            season_id: number;
            /** Processed At */
            processed_at: string;
            /** Source Manifest Sha256 */
            source_manifest_sha256: string;
            /** Rule Version */
            rule_version: string;
            /** Coverage Matches */
            coverage_matches: number;
            /** Coverage Events */
            coverage_events: number;
            /** Excluded Sequences */
            excluded_sequences: number;
            /** Excluded Spatial */
            excluded_spatial: number;
            /** Limitations */
            limitations: string[];
        };
        /** Report */
        Report: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "deterministic" | "openai";
            /** Fallback Reason */
            fallback_reason: string | null;
            /** Plan */
            plan: string[];
            input: components["schemas"]["ReportInput"];
            narrative: components["schemas"]["Narrative"];
            /** Sources */
            sources: string[];
        };
        /** ReportInput */
        ReportInput: {
            /** Rival */
            rival: string;
            /** Cutoff Date */
            cutoff_date: string;
            /** Matches */
            matches: components["schemas"]["Match"][];
            summary: components["schemas"]["Summary"];
            /** Patterns */
            patterns: components["schemas"]["Pattern"][];
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Limitations */
            limitations: string[];
        };
        /** Run */
        Run: {
            /** Run Id */
            run_id: string;
            /** Rival */
            rival: string;
            /** Analyst */
            analyst: string | null;
            /** Cutoff Date */
            cutoff_date: string;
            /** Matches */
            matches: components["schemas"]["Match"][];
            /** Dataset Version */
            dataset_version: string;
            /** Canonical Runs */
            canonical_runs?: {
                [key: string]: string;
            };
        };
        /** RunRequest */
        RunRequest: {
            /** Rival */
            rival: string;
            /** Cutoff Date */
            cutoff_date?: string | null;
            /** Target Match Id */
            target_match_id?: number | null;
            /** Analyst */
            analyst?: string | null;
            /** Expected Match Ids */
            expected_match_ids?: number[] | null;
        };
        /** Summary */
        Summary: {
            /** Rival */
            rival: string;
            /** Cutoff Date */
            cutoff_date: string;
            /** Matches */
            matches: number;
            /** Corners */
            corners: number;
            /** Evaluable Corners */
            evaluable_corners: number;
            /** Excluded Corners */
            excluded_corners: number;
            /** Shots */
            shots: number;
            /** Scr15 */
            scr15: number | null;
            /** Xg Per Corner */
            xg_per_corner: number | null;
            /** Probability */
            probability: number | null;
            /** Probability Method */
            probability_method: string;
            /** Players */
            players: components["schemas"]["Group"][];
            /** Sides */
            sides: components["schemas"]["Group"][];
            /** Deliveries */
            deliveries: components["schemas"]["Group"][];
            /** Zones */
            zones: components["schemas"]["Group"][];
        };
        /** Team */
        Team: {
            /** Name */
            name: string;
        };
        /** TemporalMetric */
        TemporalMetric: {
            /** Objective */
            objective: string;
            /** Window */
            window: string;
            /** Role */
            role: string;
            /** Model */
            model: string;
            /** N */
            n: number;
            /** Positive */
            positive?: number | null;
            /** Prevalence */
            prevalence?: number | null;
            /** Average Precision */
            average_precision?: number | null;
            /** Brier */
            brier?: number | null;
            /** Log Loss */
            log_loss?: number | null;
            /** Calibration Gap */
            calibration_gap?: number | null;
            /** Roc Auc */
            roc_auc?: number | null;
            /** Mae */
            mae?: number | null;
            /** Poisson Deviance */
            poisson_deviance?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    getTeams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"][];
                };
            };
            /** @description Artefactos canonicos no disponibles */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMatches: {
        parameters: {
            query?: {
                rival?: string | null;
                before?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Match"][];
                };
            };
            /** @description Recurso no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Solicitud no procesable */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Artefactos canonicos no disponibles */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Recurso no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflicto con la version o ventana canonica */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Solicitud no procesable */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Artefactos canonicos no disponibles */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Recurso no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflicto con la version o ventana canonica */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Artefactos canonicos no disponibles */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"];
                };
            };
            /** @description Recurso no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflicto con la version o ventana canonica */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Artefactos canonicos no disponibles */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCorners: {
        parameters: {
            query?: {
                player?: string | null;
                side?: string | null;
                delivery?: string | null;
                cluster?: number | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Corner"][];
                };
            };
            /** @description Recurso no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflicto con la version o ventana canonica */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Solicitud no procesable */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Artefactos canonicos no disponibles */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getPatterns: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pattern"][];
                };
            };
            /** @description Recurso no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflicto con la version o ventana canonica */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Artefactos canonicos no disponibles */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getQuality: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quality"];
                };
            };
            /** @description Recurso no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflicto con la version o ventana canonica */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Artefactos canonicos no disponibles */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getModel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelResult"];
                };
            };
            /** @description Recurso no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflicto con la version o ventana canonica */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Artefactos canonicos no disponibles */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getReportPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Recurso no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflicto con la version o ventana canonica */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Artefactos canonicos no disponibles */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            /** @description Recurso no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflicto con la version o ventana canonica */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Artefactos canonicos no disponibles */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    askAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Recurso no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflicto con la version o ventana canonica */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Solicitud no procesable */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Artefactos canonicos no disponibles */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
