"""Generate a noncanonical visual-identity inventory from verified stage artifacts.

The metadata is for matching artwork, never for modeling or changing the raw
source. Image candidates require individual review before being accepted.
"""
from __future__ import annotations

import json

import duckdb

from analytics.io import ROOT
from backend.repository import repository


def build_inventory() -> dict[str, object]:
    source = repository()  # verifies canonical contracts, hashes and lineage
    stage = source.stage_dirs["02"]
    events = [str(stage / record.file) for record in source.contracts["02"].all_artifacts
              if record.file.startswith("events/") and record.file.endswith(".parquet")]
    if len(events) != 380:
        raise ValueError("expected_380_verified_event_partitions")
    with duckdb.connect(":memory:") as connection:
        rows = connection.execute(
            "SELECT DISTINCT CAST(player_id AS BIGINT), player, CAST(team_id AS BIGINT) "
            "FROM read_parquet(?) WHERE player_id IS NOT NULL AND player IS NOT NULL "
            "AND team_id IS NOT NULL ORDER BY 1, 3", [events]
        ).fetchall()
    players: dict[int, dict[str, object]] = {}
    names: dict[str, int] = {}
    for player_id, name, team_id in rows:
        player_id, name, team_id = int(player_id), str(name), int(team_id)
        if name in names and names[name] != player_id:
            raise ValueError("player_name_ambiguous")
        names[name] = player_id
        previous = players.setdefault(player_id, {"id": player_id, "name": name, "team_ids": []})
        if previous["name"] != name:
            raise ValueError("player_id_ambiguous")
        previous["team_ids"].append(team_id)
    clubs: dict[int, str] = {}
    for row in source.rows("corners_engineered"):
        team_id, name = int(row["team_id"]), str(row["team"])
        if team_id in clubs and clubs[team_id] != name:
            raise ValueError("club_id_ambiguous")
        clubs[team_id] = name
    match_names = {str(row[key]) for row in source.rows("matches_clean")
                   for key in ("home_team", "away_team")}
    if set(clubs.values()) != match_names or len(clubs) != 20 or len(players) != 539:
        raise ValueError("visual_identity_coverage_mismatch")
    if any(team_id not in clubs for player in players.values() for team_id in player["team_ids"]):
        raise ValueError("visual_player_club_unknown")
    return {
        "provider": "StatsBomb Open Data", "competition": "LaLiga 2015/16",
        "clubs": [{"id": team_id, "name": name} for team_id, name in sorted(clubs.items())],
        "players": list(players.values()),
    }


def main() -> None:
    payload = build_inventory()
    inventory = ROOT / "docs" / "visual-inventory.json"
    inventory.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    club_lines = [f"  {item['id']}: {json.dumps(item['name'], ensure_ascii=False)},"
                  for item in payload["clubs"]]
    player_lines = [f"  {item['id']}: {json.dumps(item['name'], ensure_ascii=False)},"
                    for item in payload["players"]]
    catalog = ROOT / "frontend" / "src" / "app" / "core" / "visual-entities.generated.ts"
    catalog.write_text("// Generated by scripts/build_visual_inventory.py; identity only, no image rights implied.\n"
                       + "export const clubNames:Record<number,string> = {\n" + "\n".join(club_lines)
                       + "\n};\nexport const playerNames:Record<number,string> = {\n"
                       + "\n".join(player_lines) + "\n};\n", encoding="utf-8")
    print(f"Visual identities: {len(payload['clubs'])} clubs, {len(payload['players'])} players")


if __name__ == "__main__":
    main()
