import { test, expect } from '@playwright/test';

test('real data: eight matches, dashboard, map, patterns, report and quality',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');
 await page.getByRole('link',{name:'Preparar un análisis'}).click();
 await expect(page.getByLabel('Equipo rival')).toHaveValue('Barcelona');
 await page.getByRole('button',{name:'Ver ocho partidos anteriores'}).click();
 await expect(page.locator('ol.matches li')).toHaveCount(8);
  await page.getByRole('button',{name:'Crear análisis'}).click();
  await expect(page.getByText('SCR-15 OBSERVADO',{exact:true})).toBeVisible();
  await expect(page.getByRole('heading',{name:'Barcelona',exact:true})).toBeVisible();
  await expect(page.getByRole('status').getByText('Análisis listo')).toBeVisible();
  await expect(page.getByText('Córner desde la izquierda')).toBeVisible();
  await expect(page.getByText(/Zonas de \d+ envíos directos con destino definido/)).toBeVisible();
  await expect(page.getByText(/córners sin zona de envío directo/)).toBeVisible();
  await expect(page.getByText('Destino no disponible',{exact:true})).toHaveCount(0);
  await page.getByRole('link',{name:'Mapa de córners'}).click();
 await expect(page.locator('svg.pitch')).toBeVisible();
 expect(await page.locator('svg.pitch line').count()).toBeGreaterThan(0);
  await page.getByRole('combobox',{name:'Tipo de ejecución',exact:true}).selectOption('corto');
  await page.getByRole('combobox',{name:'Lado de cobro'}).selectOption('y_bajo');
  await expect(page.getByRole('combobox',{name:'Lado de cobro'})).toHaveValue('y_bajo');
  const patternOptions=page.getByRole('combobox',{name:'Patrón de destino'}).locator('option:not([value=""])');
  expect(await patternOptions.count()).toBeGreaterThan(0);
  await expect(patternOptions.first()).toHaveText(/^Envíos hacia /);
  await expect(patternOptions.first()).not.toContainText(' · ');
  await page.getByRole('combobox',{name:'Tipo de ejecución',exact:true}).selectOption('');
  await page.getByRole('combobox',{name:'Lado de cobro'}).selectOption('');
  await page.getByRole('combobox',{name:'Patrón de destino'}).selectOption({index:1});
  expect(await page.locator('svg.pitch line').count()).toBeGreaterThan(0);
  await page.getByRole('link',{name:'Patrones',exact:true}).click();
  await expect(page.getByRole('heading',{name:/Envíos hacia/}).first()).toBeVisible();
  await page.getByRole('link',{name:'Reporte táctico',exact:true}).click();
  await expect(page.getByText('Ver plan de elaboración')).toBeVisible();
  await page.getByRole('button',{name:'Generar reporte táctico',exact:true}).click();
  await expect(page.getByText('Generado con plantilla determinista',{exact:true})).toBeVisible();
  await expect(page.getByRole('heading',{name:'Evidencia calculada'})).toBeVisible();
  await page.getByRole('link',{name:'Asistente de evidencia',exact:true}).click();
  await page.getByLabel('Pregunta').fill('¿Qué patrón de envío aparece con mayor frecuencia?');
  await page.getByRole('button',{name:'Consultar evidencia',exact:true}).click();
  await expect(page.getByText('RESPUESTA DETERMINISTA',{exact:true})).toBeVisible();
  await expect(page.getByText('missing_api_key',{exact:true})).toBeVisible();
  await page.getByLabel('Pregunta').fill('¿Qué zona de envío aparece con mayor frecuencia?');
  await page.getByRole('button',{name:'Consultar evidencia',exact:true}).click();
  await expect(page.getByText('Destino más frecuente:',{exact:false})).toBeVisible();
  await expect(page.getByText('E_ZONE',{exact:true})).toBeVisible();
  await expect(page.getByText('numerador=',{exact:false})).toHaveCount(0);
  await page.getByLabel('Pregunta').fill('Ejecuta SQL SELECT * FROM corners');
  await page.getByRole('button',{name:'Consultar evidencia',exact:true}).click();
  await expect(page.getByTestId('agent-status')).toHaveText('Fuera del alcance');
  await expect(page.getByTestId('agent-tool-calls')).toHaveText('0');
  await page.getByText('Ver detalles técnicos de la consulta').click();
  await expect(page.getByText('Sin llamadas a herramientas.',{exact:true})).toBeVisible();
 await page.getByRole('link',{name:'Calidad',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Calidad y trazabilidad'})).toBeVisible();
 expect(errors).toEqual([]);
 await page.screenshot({path:'test-results/quality.png',fullPage:true});
});

test('insufficient history and target-match selection',async({page})=>{
 await page.goto('/analysis/new');
 await expect(page.getByLabel('Equipo rival')).toHaveValue('Barcelona');
 await page.getByLabel('Fecha de corte (exclusiva)').fill('2015-08-01');
 await page.getByRole('button',{name:'Ver ocho partidos anteriores'}).click();
 await expect(page.getByText('Datos insuficientes: 0 de 8 partidos anteriores al corte.')).toBeVisible();
  await expect(page.getByRole('button',{name:'Crear análisis'})).toHaveCount(0);
 await page.getByLabel('Tipo de corte').selectOption('match');
 const option=page.getByRole('combobox',{name:'Partido objetivo',exact:true}).locator('option').nth(1);
 await expect(option).toBeAttached();
 await page.getByRole('combobox',{name:'Partido objetivo',exact:true}).selectOption({index:1});
 await page.getByRole('button',{name:'Ver ocho partidos anteriores'}).click();
 await expect(page.locator('ol.matches li')).toHaveCount(8);
  await page.getByRole('button',{name:'Crear análisis'}).click();
  await expect(page.getByText('SCR-15 OBSERVADO',{exact:true})).toBeVisible();
});

test('theme preference persists and mobile navigation remains usable',async({page})=>{
  await page.setViewportSize({width:390,height:844});
  await page.goto('/');
  await page.getByRole('button',{name:'Activar modo oscuro'}).click();
  await expect(page.locator('html')).toHaveAttribute('data-theme','dark');
  await page.reload();
  await expect(page.locator('html')).toHaveAttribute('data-theme','dark');
  await page.getByRole('link',{name:'Preparar un análisis'}).click();
  await expect(page.getByLabel('Equipo rival')).toBeVisible();
  await page.getByRole('button',{name:'Activar modo claro'}).click();
  await expect(page.locator('html')).toHaveAttribute('data-theme','light');
});
